### ISSUE TITLE
Please add a note indicating that MongoDB now offers ARMv8-A support

### ISSUE THREAD

**Issue by acmorrow** [Barryrowe/mongo-arm#1]
The ticket you mentioned, https://jira.mongodb.org/browse/SERVER-1811, has been resolved in the latest development version of MongoDB, 3.3.11. Please see the most recent comments in that tickets for details on where to obtain the development release. Official support will arrive in MongoDB 3.4 GA, expected later this year.

I'm not familiar enough with the current happenings in the Pi space to know, but my understanding is that more recent models can run 64-bit ARM binaries.

If that is true, and especially if you are no longer currently maintaining this, would you mind updating your README to reflect the new status? This page is highly ranked for google queries related to "mongodb arm", and I think it would be useful to get the word out about the work that we have done.

Thanks!

**Comment by Barryrowe** [comment]
Awesome, thanks for letting me know. I'll update the README.

**Comment by acmorrow** [comment]
Thanks for the quick update!
